# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
require 'nokogiri'

default_platform(:ios)

platform :ios do

#region Certificates
  desc 'Generate certificates'
  lane :generate_certificates do |options|
    app_bundles = ['com.nordic-it.mark5.mobile.ios',
                   'com.nordic-it.mark5.mobile.ios.callid',
                   'com.nordic-it.mark5.mobile.ios.share']

    sync_code_signing(
      type: options[:type],
      app_identifier: app_bundles,
      force_for_new_devices: true,
      readonly: false
    )
  end
#endregion 

#region Versioning
  def version
    get_info_plist_value(path: './Mark5.Mobile.IOS/Info.plist',
                         key: 'CFBundleShortVersionString')
  end

  def build_number
    get_info_plist_value(path: './Mark5.Mobile.IOS/Info.plist',
                         key: 'CFBundleVersion')
  end
#endregion

#region Build 
  def update_entitlements
    update_plist(
      plist_path: './Mark5.Mobile.IOS/Entitlements.plist',
      block: proc do |plist|
        plist[:"aps-environment"] = 'production'
        plist[:"com.apple.developer.icloud-container-environment"] = 'Production'
      end
    )
  rescue StandardError => e
    slack_on_error(e)
  end

  desc 'Build iOS app release'
  lane :build_release do |options|
    begin
      bump_version(platform: 'iOS', type: options[:version_type], info_plist_pathes: ENV['INFO_PLIST_PATHES'])
      bump_code(platform: 'iOS', info_plist_pathes: ENV['INFO_PLIST_PATHES'])
      update_entitlements
      nuget(
        sln: 'Mark5.sln',
        verbosity: 'detailed'
      )
      msbuild(
        solution: './Mark5.sln',
        platform: 'iPhone',
        target: options[:target].nil? ? 'Rebuild' : options[:target],
        build_type: 'Release',
        ipa_name: 'remark.ipa'
      )
      slack_on_success
    rescue StandardError => e
      slack_on_error(e)
    end
  end
#endregion

#region Slack
  def slack_on_success(message)
    slack(
      slack_url: ENV['SLACK_URL'],
      message: message,
      channel: ENV['SLACK_CHANNEL'],
      success: true,
      attachment_properties: { fields: [{ title: 'Version', value: get_version },
                                        { title: 'Build number', value: get_build_number }] }
    )
  end

  def slack_on_error(exception)
    slack(
      slack_url: ENV['SLACK_URL'],
      message: 'Error occured ☹️!',
      channel: ENV['SLACK_CHANNEL'],
      success: false,
      attachment_properties: { fields: [{ title: 'Error message', value: exception }] }
    )
  end
#endregion

#region Deliver
  submission_information = {
    add_id_info_limits_tracking: false,
    add_id_info_serves_ads: false,
    add_id_info_tracks_action: false,
    add_id_info_tracks_install: false,
    add_id_info_uses_idfa: false,
    content_rights_has_rights: true,
    content_rights_contains_third_party_content: true,
    export_compliance_platform: 'ios',
    export_compliance_compliance_required: false,
    export_compliance_encryption_updated: false,
    export_compliance_app_type: nil,
    export_compliance_uses_encryption: false,
    export_compliance_is_exempt: false,
    export_compliance_contains_third_party_cryptography: false,
    export_compliance_contains_proprietary_cryptography: false,
    export_compliance_available_on_french_store: false
  }

  desc 'Upload to Testflight'
  lane :release_beta do |options|
    begin
      groups = options[:type] == 'internal' ? ['internal'] : ['all']
      app_store_connect_api_key
      pilot(
        changelog: options[:changelog],
        distribute_external: true,
        distribute_only: false,
        ipa: './Mark5.Mobile.IOS/bin/iPhone/Release/remark.ipa',
        groups: groups,
        skip_submission: false,
        skip_waiting_for_build_processing: false
      )
      slack_on_success('reMARK iOS app successfully uploaded to Testflight 📱')
    rescue StandardError => e
      slack_on_error(e)
    end
  end

  desc 'Upload to AppStore'
  lane :release do
    begin
      deliver(
        api_key: app_store_connect_api_key,
        app_version: version,
        app_identifier: 'com.nordic-it.mark5.mobile.ios',
        ipa: './Mark5.Mobile.IOS/bin/iPhone/Release/remark.ipa',
        submit_for_review: true,
        automatic_release: true,
        phased_release: true,
        force: true, # Skip HTMl report verification
        skip_metadata: false,
        skip_screenshots: true,
        skip_binary_upload: false,
        run_precheck_before_submit: false,
        submission_information: submission_information
      )
      slack_on_success('reMARK iOS app successfully uploaded to AppStore 📱')
    rescue StandardError => e
      slack_on_error(e)
    end
  end
#endregion
end

platform :android do

#region Versioning

  def version
    File.open(ENV['ANDROID_MANIFEST_PATH']) do |f|
      @doc = Nokogiri::XML(f)
      current_version = @doc.at('//manifest/@android:versionName').text
      return current_version.to_s
    end
  end

  def build_number
    File.open(ENV['ANDROID_MANIFEST_PATH']) do |f|
      @doc = Nokogiri::XML(f)
      current_build = @doc.at('//manifest/@android:versionCode').text
      return current_build.to_s
    end
  end

#endregion

#region Build

  desc 'Build Android app release'
  lane :build_release do |options|
    begin
      bump_version(platform: 'Android', type: options[:version_type], manifest_file_path: ENV['ANDROID_MANIFEST_PATH'])
      bump_code(platform: 'Android', manifest_file_path: ENV['ANDROID_MANIFEST_PATH'])
      nuget(
        sln: 'Mark5.sln',
        verbosity: 'detailed'
      )
      msbuild(
        project: './Mark5.Mobile.Droid/Mark5.Mobile.Droid.csproj',
        target: options[:target].nil? ? 'Rebuild' : options[:target],
        build_type: 'Release',
        sign_apk: true,
        android_signing_keystore: ENV['PATH_TO_KEYSTORE'],
        android_signing_key_alias: 'default',
        android_signing_key_pass: 'Xs4Droid2015!',
        android_signing_store_pass: 'Xs4Droid2015!'
      )
    rescue StandardError => e
      slack_on_error(e)
    end
  end

#endregion

#region Deliver
  desc 'Upload beta release to Google Play beta'
  lane :release_beta do
    begin
      supply(
        apk: './Mark5.Mobile.Droid/bin/Release/com.nordic_it.mark5.android-Signed.apk',
        track: 'beta',
        skip_upload_images: true,
        skip_upload_screenshots: true,
        package_name: 'com.nordic_it.mark5.android',
        version_name: version,
        version_code: build_number
      )
      slack_on_success('reMark Android app was succcessfully uploaded to Google beta')
    rescue StandardError => e
      slack_on_error(e)
    end
  end

  desc 'Upload release to Google Play'
  lane :release do
    begin
      supply(
        apk: './Mark5.Mobile.Droid/bin/Release/com.nordic_it.mark5.android-Signed.apk',
        track: 'rollout',
        rollout: '0.5',
        skip_upload_images: true,
        skip_upload_screenshots: true,
        package_name: 'com.nordic_it.mark5.android',
        version_name: version,
        version_code: build_number
      )
      slack_on_success('reMark Android app was succcessfully uploaded to Google beta')
    rescue StandardError => e
      slack_on_error(e)
    end
  end
#endregion
end
