# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Get certificates"
  lane :certificates do
    sync_code_signing(
      type: "development",
      app_identifier: ['com.nordic-it.mark5.mobile.ios', 'com.nordic-it.mark5.mobile.ios.callid', 'com.nordic-it.mark5.mobile.ios.share'],
      force_for_new_devices: true,
      readonly: true
    )

    # You can repeat the sync_code_signing with other types of certificates such as appstore and adhoc
    sync_code_signing(
      type: "appstore",
      app_identifier: ['com.nordic-it.mark5.mobile.ios', 'com.nordic-it.mark5.mobile.ios.callid', 'com.nordic-it.mark5.mobile.ios.share'],
      readonly: true
    )
  end

  desc "Generate new certificates"
  lane :generate_new_certificates do
    sync_code_signing(
      type: "development",
      app_identifier: ['com.nordic-it.mark5.mobile.ios', 'com.nordic-it.mark5.mobile.ios.callid', 'com.nordic-it.mark5.mobile.ios.share'],
      force_for_new_devices: true,
      readonly: false
    )
    
     sync_code_signing(
      type: "appstore",
      app_identifier: ['com.nordic-it.mark5.mobile.ios', 'com.nordic-it.mark5.mobile.ios.callid', 'com.nordic-it.mark5.mobile.ios.share'],
      readonly: false
    )

      sync_code_signing(
      type: "adhoc",
      app_identifier: ['com.nordic-it.mark5.mobile.ios', 'com.nordic-it.mark5.mobile.ios.callid', 'com.nordic-it.mark5.mobile.ios.share'],
      force_for_new_devices: true,
      readonly: false
    )
  end

  def bump_version(current_version,type)
    components = current_version.split('.')
    major = components[0].to_i
    minor = components[1].to_i
    patch = components[2].to_i

    if type == "major"
      major += 1
      minor = 0
      patch = 0
    elsif type == "minor"
      minor += 1
      patch = 0
    elsif type == "patch"
      patch += 1
    else
      abort("Unknown version bump type: #{type}\nValid options: major, minor, patch.")
    end

    return new_version = [major, minor, patch].join('.')
  end

  def bump_build_version(type)
    build_number = get_info_plist_value(path: "./Mark5.Mobile.IOS/Info.plist", key: "CFBundleVersion")
    new_build_number = build_number.to_i+1
    set_info_plist_value(path: "./Mark5.Mobile.IOS/Info.plist", key: "CFBundleVersion", value: new_build_number.to_s)
    set_info_plist_value(path: "./Mark5.Mobile.IOS.Extensions.CallId/Info.plist", key: "CFBundleVersion", value: new_build_number.to_s)
    set_info_plist_value(path: "./reMARK.Mobile.IOS.Extensions.Share/Info.plist", key: "CFBundleVersion", value: new_build_number.to_s)
    
    current_version = get_info_plist_value(path: "./Mark5.Mobile.IOS/Info.plist", key: "CFBundleShortVersionString")
    
    new_version = bump_version(current_version, type)

    set_info_plist_value(path: "./Mark5.Mobile.IOS/Info.plist", key: "CFBundleShortVersionString", value: new_version)
    set_info_plist_value(path: "./Mark5.Mobile.IOS.Extensions.CallId/Info.plist", key: "CFBundleShortVersionString", value: new_version)
    set_info_plist_value(path: "./reMARK.Mobile.IOS.Extensions.Share/Info.plist", key: "CFBundleShortVersionString", value: new_version)
 
 end 

  def bump_droid_build_version(type)
    require 'nokogiri'
    manifest_file = '/Users/anna/mark5-app-new/Mark5.Mobile.Droid/Properties/AndroidManifest.xml'
    doc = File.open(manifest_file) { |f|
      @doc = Nokogiri::XML(f)
      manifest_node = @doc.xpath('//manifest')
      current_version = @doc.at('//manifest/@android:versionName').text
      new_version = bump_version(current_version, type)
      current_build = @doc.at('//manifest/@android:versionCode').text
      new_build = (current_build.to_i+1).to_s
      puts new_version
      puts new_build
      manifest_node.attr('android:versionName', new_version)
      manifest_node.attr('android:versionCode', new_build)
      File.write(manifest_file, @doc.to_xml)
    }
  end


 def post_to_slack
  slack(
    slack_url: "https://hooks.slack.com/services/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",
    message: "App successfully released!",
    channel: "#fastlane", 
    success: true,  
    username: "ag"
    )
end

 def nuget(sln)
    sh "nuget restore #{sln} -verbosity detailed"
end
  
  desc "Build beta version"
  lane :build_beta do
    bump_build_version("patch")
    update_plist( 
      plist_path: "./Mark5.Mobile.IOS/Entitlements.plist",
      block: proc do |plist|
        plist[:"aps-environment"] = "production"
      end
    )
    sync_code_signing(
      type: "appstore",
      app_identifier: ['com.nordic-it.mark5.mobile.ios', 'com.nordic-it.mark5.mobile.ios.callid', 'com.nordic-it.mark5.mobile.ios.share'],
      force_for_new_devices: true,
      readonly: false
    )
    nuget('/Users/anna/mark5-app-new/Mark5.sln')
    xamarin_build(
        solution: '/Users/anna/mark5-app-new/Mark5.sln',
        platform: 'iPhone',
        target: 'Rebuild',
        build_type: 'Release',
        print_all: true,
        build_util: 'msbuild',
        ipa_name: 'remark.ipa'
    )
    post_to_slack
  end


  desc "Upload beta to Testflight"
  lane :upload_beta do
     app_store_connect_api_key()
     pilot(
      changelog: "test fastlane build",
      distribute_external: true,
      distribute_only: false,
      ipa: "./Mark5.Mobile.IOS/bin/iPhone/Release/remark.ipa",
       groups: [
            "test"
        ],
      skip_submission: false,
      skip_waiting_for_build_processing: false
    ) 
  end

  desc "Bump Android version"
  lane :bump_droid do
    bump_droid_build_version('patch')
  end

  desc "Build Android app"
  lane :build_droid do
    nuget('/Users/anna/mark5-app-new/Mark5.sln')
    bump_droid_version('patch')
    xamarin_build(
        solution: '/Users/anna/mark5-app-new/Mark5.sln',
        platform: '',
        target: 'Rebuild',
        build_type: 'Release',
        print_all: true,
        build_util: 'msbuild',
        ipa_name: 'remark.ipa'
    )
  end
    

end

